In [6]:
import pandas as pd
from ta.trend import EMAIndicator
from ta.momentum import RSIIndicator
from ta.trend import MACD
from ta.volatility import BollingerBands
from ta.momentum import StochasticOscillator
from ta.volatility import AverageTrueRange
from ta.trend import ADXIndicator

In [2]:
df = pd.read_csv("../data/EURUSD_H4_clean.csv", parse_dates=["datetime"])

In [3]:
# EMA
ema_periods = [5, 10, 20, 50, 100, 200]
for period in ema_periods:
    df[f"ema_{period}"] = EMAIndicator(close=df["<CLOSE>"], window=period).ema_indicator()

In [4]:
# RSI
rsi = RSIIndicator(close=df["<CLOSE>"], window=14)
df["rsi"] = rsi.rsi()

In [5]:
# MACD 
macd = MACD(close=df["<CLOSE>"])
df["macd"] = macd.macd()
df["macd_signal"] = macd.macd_signal()
df["macd_diff"] = macd.macd_diff()

In [ ]:
# Bollinger Bands 
bb = BollingerBands(close=df["<CLOSE>"], window=20, window_dev=2)
df["bb_upper"] = bb.bollinger_hband()
df["bb_lower"] = bb.bollinger_lband()
df["bb_mid"] = bb.bollinger_mavg()
df["bb_bandwidth"] = bb.bollinger_wband()

In [8]:
# Stochastic Oscillator 
stoch = StochasticOscillator(high=df["<HIGH>"], low=df["<LOW>"], close=df["<CLOSE>"], window=14, smooth_window=3)
df["stoch_k"] = stoch.stoch()
df["stoch_d"] = stoch.stoch_signal()

In [9]:
# ATR
atr = AverageTrueRange(high=df["<HIGH>"], low=df["<LOW>"], close=df["<CLOSE>"], window=14)
df["atr"] = atr.average_true_range()

In [10]:
# ADX 
adx = ADXIndicator(high=df["<HIGH>"], low=df["<LOW>"], close=df["<CLOSE>"], window=14)
df["adx"] = adx.adx()
df["adx_pos"] = adx.adx_pos()
df["adx_neg"] = adx.adx_neg()

In [11]:
df.head()

,datetime,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,ema_5,ema_10,ema_20,ema_50,...,bb_upper,bb_lower,bb_mid,bb_bandwidth,stoch_k,stoch_d,atr,adx,adx_pos,adx_neg
0,2024-01-02 00:00:00,1.10424,1.10443,1.10341,1.10349,4438,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
1,2024-01-02 04:00:00,1.10350,1.10360,1.10165,1.10334,5889,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
2,2024-01-02 08:00:00,1.10336,1.10388,1.10106,1.10152,13826,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3,2024-01-02 12:00:00,1.10151,1.10171,1.09494,1.09527,18275,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
4,2024-01-02 16:00:00,1.09527,1.09683,1.09408,1.09506,22154,1.098547,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0

In [12]:
df.describe()

,datetime,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,ema_5,ema_10,ema_20,ema_50,...,bb_upper,bb_lower,bb_mid,bb_bandwidth,stoch_k,stoch_d,atr,adx,adx_pos,adx_neg
count,2309,2309.000000,2309.000000,2309.000000,2309.000000,2309.000000,2305.000000,2300.000000,2290.000000,2260.000000,...,2290.000000,2290.000000,2290.000000,2290.000000,2296.000000,2294.000000,2309.000000,2309.000000,2309.000000,2309.000000
mean,2024-09-27 14:58:28.012126464,1.085201,1.086630,1.083859,1.085271,12358.690342,1.085192,1.085102,1.084932,1.084436,...,1.091106,1.078732,1.084919,1.140503,50.487685,50.485373,0.002767,26.455009,21.236466,21.252934
min,2024-01-02 00:00:00,1.019320,1.021940,1.017750,1.019330,213.000000,1.021961,1.023777,1.025984,1.029624,...,1.032310,1.018414,1.025712,0.290640,0.000000,1.759074,0.000000,0.000000,0.000000,0.000000
25%,2024-05-15 04:00:00,1.070660,1.071850,1.069470,1.070660,6727.000000,1.070754,1.071035,1.070662,1.071095,...,1.075354,1.065311,1.070838,0.679392,24.768556,26.301278,0.001986,18.431751,16.165683,15.476350
50%,2024-09-26 08:00:00,1.084160,1.085350,1.083010,1.084170,10508.000000,1.083984,1.083844,1.083975,1.083481,...,1.088958,1.079610,1.083827,0.936539,51.298403,51.574624,0.002510,24.279592,20.773501,20.565154
75%,2025-02-11 12:00:00,1.097790,1.099180,1.096450,1.097840,15625.000000,1.097992,1.098328,1.097251,1.097132,...,1.104856,1.091981,1.097636,1.382459,75.634692,74.311400,0.003285,32.254003,26.057399,26.553905
max,2025-06-25 16:00:00,1.162510,1.164140,1.161090,1.162510,64168.000000,1.161122,1.159620,1.157456,1.153816,...,1.166828,1.151044,1.156448,5.810764,100.000000,99.330448,0.009849,62.579495,48.814105,49.499660
std,NaN,0.029508,0.029656,0.029443,0.029558,7675.508440,0.029413,0.029256,0.028969,0.028123,...,0.029533,0.029099,0.029055,0.716834,28.960178,26.934040,0.001107,10.843972,7.610791,7.881924

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2309 entries, 0 to 2308
Data columns (total 26 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   datetime      2309 non-null   datetime64[ns]
 1   <OPEN>        2309 non-null   float64
 2   <HIGH>        2309 non-null   float64
 3   <LOW>         2309 non-null   float64
 4   <CLOSE>       2309 non-null   float64
 5   <TICKVOL>     2309 non-null   int64
 6   ema_5         2305 non-null   float64
 7   ema_10        2300 non-null   float64
 8   ema_20        2290 non-null   float64
 9   ema_50        2260 non-null   float64
 10  ema_100       2210 non-null   float64
 11  ema_200       2110 non-null   float64
 12  rsi           2296 non-null   float64
 13  macd          2284 non-null   float64
 14  macd_signal   2276 non-null   float64
 15  macd_diff     2276 non-null   float64
 16  bb_upper      2290 non-null   float64
 17  bb_lower      2290 non-null   float64
 18  bb_mid        2290 non-null   float64
 19  bb_bandwidth  2290 non-null   float64
 20  stoch_k       2296 non-null   float64
 21  stoch_d       2294 non-null   float64
 22  atr           2309 non-null   float64
 23  adx           2309 non-null   float64
 24  adx_pos       2309 non-null   float64
 25  adx_neg       2309 non-null   float64
dtypes: datetime64[ns](1), float64(24), int64(1)
memory usage: 469.1 KB

In [14]:
df.to_csv("../data/EURUSD_with_indicators.csv", index=False)